
FT_DPCM_PTR=$c000
	.export _danger_streets_music_data
;this file for FamiTone2 library generated by text2data tool
_danger_streets_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $f0 ; 00 : Bleep
	.word @env1, @env2, @env2
	.byte $00
	.byte $70 ; 01 : BleepIntro
	.word @env5, @env2, @env2
	.byte $00
	.byte $30 ; 02 : DrumHi
	.word @env6, @env2, @env2
	.byte $00
	.byte $30 ; 03 : DrumIntro
	.word @env4, @env2, @env2
	.byte $00
	.byte $30 ; 04 : DrumMed
	.word @env0, @env2, @env2
	.byte $00
	.byte $f0 ; 05 : LeadIntro
	.word @env3, @env2, @env2
	.byte $00



@samples:
	


@env0:
	.byte $ca,$02,$c6,$03,$c2,$00,$04
@env1:
	.byte $c7,$02,$c5,$03,$c1,$00,$04
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$00,$09
@env4:
	.byte $ca,$02,$c5,$00,$02
@env5:
	.byte $c7,$06,$c1,$00,$02
@env6:
	.byte $ca,$c4,$00,$01
        
@song0ch0:
	.byte $fb, $01, $f9, $f9, $cb, $f9, $f9, $cb
@song0ref9:
	.byte $8a
@song0ref10:
	.byte $44, $cd, $68, $a5, $00, $a5, $5e, $cd, $3e, $a5, $44, $a5
	.byte $ff, $0c
	.word @song0ref10
	.byte $a7, $00, $f9, $f9, $a1
@song0ref30:
	.byte $82
@song0ref31:
	.byte $5c, $a5, $60, $a5, $5c, $a5, $60, $a5, $5c, $a5, $64, $a5, $5a, $a5, $56, $a5
@song0ch0loop:
	.byte $ff, $0c
	.word @song0ref9
	.byte $ff, $10
	.word @song0ref30
@song0ref54:
	.byte $86, $4e, $a5, $46, $a5, $4e, $a5, $00, $a5, $4e, $a5, $46, $a5, $4e, $a5, $00, $a5, $f9, $f9, $cb, $f9, $f9, $cb, $82
@song0ref78:
	.byte $4a, $a5, $00, $a5, $4a, $a5, $00, $a5, $4a, $a5, $4a, $a5, $00, $a5, $4a, $a5
	.byte $ff, $10
	.word @song0ref78
	.byte $6a, $a5, $6a, $a5, $6a, $a5, $6a, $a5, $6a, $a5, $6a, $a5, $6a, $a5, $6a, $a5
	.byte $ff, $10
	.word @song0ref78
	.byte $00, $f9, $f9, $c9, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $10
	.word @song0ref31
	.byte $fd
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $10
	.word @song0ref30
	.byte $00, $f9, $f9, $c9
@song0ref139:
	.byte $28, $a5, $2a, $a5, $28, $a5, $2a, $a5, $28, $a5, $2c, $a5, $28, $a5, $26, $a5, $00, $f9, $f9, $c9
	.byte $ff, $10
	.word @song0ref31
	.byte $ff, $0c
	.word @song0ref9
@song0ch1loop:
	.byte $ff, $10
	.word @song0ref30
	.byte $00, $f9, $f9, $c9
	.byte $ff, $10
	.word @song0ref31
	.byte $ff, $13
	.word @song0ref54
	.byte $82, $62, $a5, $5e, $a5, $5a, $a5, $54, $a5, $5a, $a5, $4e, $a5, $4a, $a5, $4a, $a5
	.byte $ff, $10
	.word @song0ref139
	.byte $ff, $10
	.word @song0ref139
	.byte $ff, $10
	.word @song0ref139
	.byte $ff, $10
	.word @song0ref139
	.byte $ff, $10
	.word @song0ref31
	.byte $ff, $10
	.word @song0ref54
	.byte $ff, $0c
	.word @song0ref9
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ref220:
	.byte $f9, $f9, $cb
@song0ref223:
	.byte $88, $56, $a5, $80, $38, $a5, $88, $56, $a5, $80, $38, $a5, $88, $56, $a5, $80, $38, $a5, $88, $56, $a5, $80, $38, $a5
	.byte $00, $f9, $f9, $c9
	.byte $ff, $13
	.word @song0ref220
	.byte $ff, $10
	.word @song0ref223
@song0ch2loop:
	.byte $ff, $10
	.word @song0ref223
	.byte $ff, $10
	.word @song0ref30
	.byte $00, $f9, $f9, $c9
	.byte $ff, $10
	.word @song0ref31
	.byte $8a, $68, $a5, $68, $a5, $68, $a5, $68, $a5, $72, $a5, $68, $a5, $76, $a5, $68, $a5, $7c, $a5, $70, $a5, $02, $a5, $02
	.byte $a5, $00, $a5, $02, $a5, $04, $a5, $08, $a5, $84
@song0ref305:
	.byte $6e, $a5, $6e, $a5, $68, $a5, $00, $a5, $6e, $a5, $00, $a5, $64, $a5, $6e, $a5
	.byte $ff, $10
	.word @song0ref305
	.byte $ff, $10
	.word @song0ref305
	.byte $ff, $10
	.word @song0ref305
	.byte $ff, $10
	.word @song0ref30
	.byte $ff, $14
	.word @song0ref223
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ref339:
	.byte $86
@song0ref340:
	.byte $66, $a5, $5e, $a5, $66, $a5, $00, $a5, $66, $a5, $5e, $a5, $66, $a5, $00
@song0ref355:
	.byte $a5, $00, $a5, $80, $78, $a5, $5c, $a5, $78, $a5, $68, $a5, $7e, $a5, $6e, $a5, $00, $a5
	.byte $ff, $10
	.word @song0ref339
	.byte $ff, $20
	.word @song0ref340
	.byte $ff, $10
	.word @song0ref339
@song0ch3loop:
	.byte $ff, $10
	.word @song0ref339
	.byte $ff, $10
	.word @song0ref340
@song0ref389:
	.byte $82, $74, $a5, $78, $a5, $74, $a5, $78, $a5, $74, $a5, $7c, $a5, $72, $a5, $6e, $a5, $00, $f9, $f9, $c9, $84
@song0ref411:
	.byte $52, $a5, $60, $a5, $4c, $a5, $56, $a5, $4e, $a5, $00, $a5, $5e, $a5, $00, $a5
	.byte $ff, $10
	.word @song0ref411
	.byte $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $10
	.word @song0ref411
	.byte $f9, $f9, $cb, $06, $a5, $06, $a5, $00, $a5, $00, $a5, $06, $a5, $00, $a5, $7c, $a5, $06
	.byte $ff, $11
	.word @song0ref355
	.byte $ff, $10
	.word @song0ref389
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ref466:
	.byte $f9, $f9, $cb, $f9, $f9, $cb
@song0ref472:
	.byte $f9, $f9, $cb, $00, $f9, $f9, $c9, $f9, $f9, $cb, $00, $f9, $f9, $c9
@song0ch4loop:
	.byte $ff, $0a
	.word @song0ref472
	.byte $ff, $0a
	.word @song0ref472
	.byte $f9, $f9, $cb
	.byte $ff, $14
	.word @song0ref466
	.byte $fd
	.word @song0ch4loop
